{
 "title": "FID Dashboard",
 "description": "Dashboard to monitor key metrics from fid-exporter",
 "tags": [
  "fid",
  "radiantone"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(ldap_monitor_starttime,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Used",
   "type": "stat",
   "description": "The current amount of system CPU utilized",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ldap_cpu_used{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "description": "JVM Memory used(Note: This is not the actual machine memory)",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ldap_memory_used{instance=~\"$node\",job=\"fid-targets\"} / ldap_memory_max{instance=~\"$node\",job=\"fid-targets\"}) * 100"
    },
    {}
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "description": "Current amount of machine disk-space used",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ldap_disk_used{instance=~\"$node\",job=\"fid-targets\"}/ ldap_disk_total{instance=~\"$node\",job=\"fid-targets\"})*100"
    },
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ldap_server_version{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "Server Current Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ldap_monitor_currenttime{instance=~\"$node\",job=\"fid-targets\"}*1000"
    }
   ]
  },
  {
   "title": "FID Pool",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ldap_current_pool_size_anonymous{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_current_pool_size_simple{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_current_pool_size_digest{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "description": "Time elapsed since the server is started",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-ldap_monitor_starttime{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "Live Connections",
   "type": "stat",
   "description": "The live number of concurrent connections to RadiantOne FID (will never be more than connectionMax). This number increases or decreases depending on new connections coming into RadiantOne FID or existing connections being closed",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ldap_current_connections{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "OPS",
   "type": "stat",
   "description": "search, bind, compare, add, delete, or modify (op/s) rate during the last 5 seconds",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ldap_write_ops{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_read_ops{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "Peak Stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ldap_cpu_peak{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_connection_peak{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_memory_peak{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_disk_peak{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "Operations Count",
   "type": "stat",
   "description": "The total number of operations RadiantOne FID has done on the connection",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ldap_operation_count{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ldap_cpu_used{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "ldap_memory_used{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "Process Queue 1 SSL/non-SSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ldap_pq_1_non_ssl_num_operations_executing{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_1_non_ssl_num_operations_waiting{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_1_ssl_num_operations_executing{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_1_ssl_num_operations_waiting{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_1_non_ssl_thread_pool_max_size{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_1_ssl_thread_pool_max_size{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "Process Queue 2 SSL/non-SSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "ldap_pq_2_non_ssl_num_operations_executing{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_2_non_ssl_num_operations_waiting{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_2_ssl_num_operations_executing{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_2_ssl_num_operations_waiting{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_2_non_ssl_thread_pool_max_size{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_2_ssl_thread_pool_max_size{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  },
  {
   "title": "Process Queue INTL SSL/non-SSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "ldap_pq_intl_non_ssl_num_operations_executing{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_intl_non_ssl_num_operations_waiting{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_intl_ssl_num_operations_executing{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_intl_ssl_num_operations_waiting{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_intl_non_ssl_thread_pool_max_size{instance=~\"$node\",job=\"fid-targets\"}"
    },
    {
     "expr": "ldap_pq_intl_ssl_thread_pool_max_size{instance=~\"$node\",job=\"fid-targets\"}"
    }
   ]
  }
 ]
}