version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200"
    networks:
      fid-net:
        aliases:
          - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 60s
      timeout: 10s
      retries: 10
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    ports:
      - "5601:5601"
    networks:
      fid-net:
        aliases:
          - kibana
  prometheus:
    image: prom/prometheus:v2.29.2
    hostname: "prometheus"
    volumes:
      - ./configs/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always
    networks:
      fid-net:
        aliases:
          - prometheus
  pushgateway:
    image: prom/pushgateway
    hostname: "pushgateway"
    ports:
      - "9091:9091"
    restart: always
    networks:
      fid-net:
        aliases:
          - pushgateway
    volumes:
      - pushgateway:/data
    command: --persistence.file="/data/metric.store"
  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana:/etc/grafana
    env_file:
      - ./configs/grafana/config.monitoring
    restart: always
    networks:
      fid-net:
        aliases:
          - grafana
  alertmanager:
    image: prom/alertmanager
    hostname: "alertmanager"
    ports:
      - "9093:9093"
    volumes:
      - ./configs/alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      fid-net:
        aliases:
          - alertmanager